[project]
name = "photo-relay-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.3",
    "rembg>=2.0.59",
]
